FROM python:3.8

WORKDIR /usr/source/app

COPY ./sources/microservice_a.py ./

COPY ./sources/requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt
COPY . .

EXPOSE 8080
CMD [ "python", "./microservice_a.py" ]