FROM alpine:latest
MAINTAINER john.urbano@correo.icesi.edu.co

RUN apk --no-cache upgrade
RUN apt add --no-cache apache2
RUN echo "ServerName localhost" >> /etc/apache2/apache2.conf
COPY . /var/www/html/
EXPOSE 80
RUN apt install -y wget
RUN apt install -y curl

RUN mkdir WORKDIR /var/www/html/
RUN rm -f index.html
RUN wget www.icesi.edu.co

CMD ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]
