version: '3.7'
services:
  
  mysql:
    image: mysql:5.7
    ports:
     - "3306:3306"
    restart: always
    environment:
   #  MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_PASSWORD: dummypassword 
      MYSQL_USER: todos-user
      MYSQL_PASSWORD: dummytodos
      MYSQL_DATABASE: todos
   
    image: icesiops/todo-web-application-mysql:0.0.1-SNAPSHOT
    ports:
     - "8080:8080"
    restart: always
    depends_on:
     - mysql
    environment:
     RDS_HOSTNAME: mysql
   # RDS_PORT: 3306
   # RDS_DB_NAME: todos
   # RDS_USERNAME: todos-user
   # RDS_PASSWORD: dummytodos

 
